site:
  title: CentOS Documentation
  start_page: stream-contrib:ROOT:index.adoc
content:
  sources:
   - url: .
     branches: HEAD
ui:
  bundle:
    url: https://docs.centos.org/_bundle/ui-bundle.zip
    snapshot: true
  default_layout: default
output:
  clean: true
  dir: ./public
  destinations:
  - provider: archive
runtime:
  pull: true
  cache_dir: ./cache
